% Convenience script for running a single test.

addpaths;
close all; clear; clc;
global l1
global epsilon
global lambda
l1 = 1;
epsilon = 0.01;
lambda = 1;
%test_result = runtest('mmp',struct(),'linearmdp',...
%    'objectworld',struct('n',32,'determinism',0.7,'seed', sum(100*clock), 'continuous',0, 'policy_type','lawful'),...
%    struct('training_sample_lengths', 32, 'training_samples', 512, 'verbosity',2));

% Visualize solution.
%printresult(test_result);
%visualize(test_result);

%{
test_result = runtest('mmp',struct(),'linearmdp',...
    'highway',struct(...
    'seed',0,...
    'length',2,...
    'lanes',2,...
    'speeds',4,...
    'num_cars',[2 2],...
    'c1',2,...
    'c2',2,...
    'continuous',0,...
    'determinism',1.0,...
    'policy_type','outlaw',...
    'discount',0.9),...
    struct('training_sample_lengths', 3, 'training_samples', 512, 'verbosity',2));
 
% Visualize solution.
printresult(test_result);
visualize(test_result);
%}

test_result = runtest('gpirl',struct(),'linearmdp',...
    'toyota',struct(...
    'seed',0,...
    'lanes', 2,...
    'distance', 3,...%8,...
    'speed', 4,...%6,...
    'num_cars', 2,...
    'continuous',0,...
    'determinism',1.0,...
    'policy_type','outlaw',...
    'discount',0.9),...
    struct('training_sample_lengths', 3, 'training_samples', 100, 'verbosity',2));
 
% Visualize solution.
printresult(test_result);
%visualize(test_result);
cur_time = datestr(now,'HH_MM_SS');
file_name = strcat(strcat('toyota_result_', cur_time), '.mat');
save(file_name, '-struct', 'test_result');
policy = test_result.irl_result.p;
file_name = strcat(strcat('toyota_policy_', cur_time), '.mat');
save(file_name, 'policy');

% For deepGPIRL
%runtest('deepgpirl',struct(),'linearmdp','binaryworld',struct('n',12),...
%    struct('training_sample_lengths',12^2,'training_samples',8,'verbosity',1));
