% Fill in default parameters for the toyota example.
function mdp_params = toyotadefaultparams(mdp_params)

% Create default parameters.
default_params = struct(...
    'seed', 0,...
    'lanes', 2,...
    'distance', 8,...
    'speed', 6,...
    'num_cars', 2,...
    'determinism', 1.0,...
    'discount', 0.9);

% Set parameters.
mdp_params = filldefaultparams(mdp_params, default_params);

